# Generated by Django 5.2.3 on 2025-10-02 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='full_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='ful_description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='short_description',
        ),
    ]
