# Generated by Django 5.2.8 on 2025-11-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_contact_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievements', models.CharField(blank=True, max_length=100, null=True)),
                ('education_description', models.TextField(blank=True, null=True)),
                ('education_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='skill',
            name='education',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='education_date',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='education_description',
        ),
    ]
